apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nrpe-exporter-allow-privileged
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  resourceNames:
  - anyuid
  - privileged
  verbs:
  - use
