apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nrpe-exporter-allow-privileged
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nrpe-exporter-allow-privileged
subjects:
- kind: ServiceAccount
  name: nrpe-exporter
