apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: internal-ca-cert
spec:
  isCA: true
  commonName: internal-ca
  secretName: internal-ca-cert
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer

  subject:
    organizations:
      - internal
