apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nrpe-exporter
commonLabels:
  app: nrpe-exporter

resources:
  - certificate.yaml
  - daemonset.yaml
  - namespace.yaml
  - secret.yaml
  - serviceaccount.yaml
  - servicemonitor.yaml
  - service.yaml
  - internal-ca
  - rbac

configurations:
  - transformers/commonLabels.yaml
